### ISSUE TITLE
Georeferrencing images

### ISSUE THREAD

**Issue by pesekon2** [jremillard/images-to-osm#3]
Hi, 

thank you for your work, it's amazing and very useful. 

However, is there any way to make georeferrenced images from the ones with masks? And if we use the detection on georeferrenced images, will this georeferrencing be preserved or not? 

Thank you in advance.

**Comment by jremillard** [comment]
Hi, I am not sure I understand the question. When the masks are found, they are eventually converted back to lat, lon?

**Comment by pesekon2** [comment]
I was interested in GeoTIFF with georeferrencing in the metadata. The ones with georeferrencing in separate files are okay (we can use the georefferencing file on the mask itself) but when we use metadata encoded GeoTIFF and insert the mask into that picture using skimage, is there any way to preserve the georefferencing?

**Comment by jremillard** [comment]
You would have to do some coding, but GeoTIFF's could be made to work.

**Comment by pesekon2** [comment]
Okay, I will try. Thanks.
