### ISSUE TITLE
Mask_RCNN submodule on an unknown commit SHA1

### ISSUE THREAD

**Issue by hy9be** [jremillard/images-to-osm#4]
https://github.com/matterport/Mask_RCNN/tree/eff135fc7bdd68511c121d06e40c13ab793bf2a2, does not exist anymore. Do you want to update the submodule?

Or maybe using the HEAD of Mask_RCNN repo is sufficient?

Please shed some lights. Thanks!

**Comment by jremillard** [comment]
I have slightly modified the Mass_RCNN repo, it may be the cause of hash differences. The current head of Mass_RCNN should work, but there are a bunch of PR queued up that might break it. If that happens, please use my Mass_RCNN fork.

**Comment by jremillard** [comment]
Switched over module to use branched Mask_RCNN
