### ISSUE TITLE
Can't download requirement!

### ISSUE THREAD

**Issue by ryujaehun** [jremillard/images-to-osm#8]
Can't download requirement! 
Maybe can't be download in ubuntu 16.04 system(python3.6)?

**Comment by jremillard** [comment]
You need python 3.6 in virtual env.

**Comment by ryujaehun** [comment]
![image](https://user-images.githubusercontent.com/22635090/39080820-fdd807e6-4570-11e8-8850-58edc3728cf2.png)
i tried to virtual env but can't download requirement

**Comment by baristahell** [comment]
I actually have the same problem, even in an fresh new env with python 3.6.

![imgosm](https://user-images.githubusercontent.com/24407720/43273383-93048d2c-90fc-11e8-86b6-152cafaefc4d.png)
